from __future__ import annotations

from app.models import AppEdition, CompetitionDefinition, TaskDefinition

STANDARD_OUTPUTS = [
    "README.md",
    "train.py",
    "predict.py",
    "run.py",
    "run_on_unihiker.py",
    "setup_unihiker.sh",
    "deploy.sh",
    "deploy.bat",
    "notebook.ipynb",
    "ai_runtime/__init__.py",
    "ai_runtime/core.py",
    "hardware/README.md",
    "requirements.txt",
    "submission/README.md",
    "docs/competition_checklist.md",
    "docs/ai_validation.md",
    "speech/README.md",
    "speech/speech_output.py",
    "speech/voice_config.json",
    "creative_examples/01_display_result.py",
    "creative_examples/02_trigger_buzzer.py",
    "creative_examples/03_count_and_log.py",
    "creative_examples/04_servo_control.py",
]


SMART_MUSEUM_TASKS = [
    TaskDefinition(
        slug="heritage_face_intro",
        title="挑战一：认识非遗传承匠人",
        summary="为人脸卡片识别和人物介绍播报生成程序骨架。",
        student_goal="生成符合“这是XXX，XXX”格式的识别结果展示和播报模板。",
        group="小学/初中/高中",
        requirement_source="附件5 智能博物 常规挑战一",
        competition_requirements=[
            "识别任务一卡片触发挑战",
            "实时拍照识别人脸卡片",
            "使用人脸识别AI技能",
            "小学播报：这是XXX",
            "初中/高中播报：这是XXX，XXX",
        ],
        ai_capability="image_classifier",
        sample_dataset_kind="image",
        runtime_requirements=["scikit-learn", "joblib", "numpy", "pillow", "onnxruntime"],
        voice_profile="dfrobot_tts_broadcast",
        paused_features=["摄像头实时拍照"],
        suggested_hardware=["unihiker_m10"],
        required_outputs=STANDARD_OUTPUTS,
        starter_steps=[
            "添加人物类别并上传卡片照片",
            "点击训练查看准确率",
            "上传新卡片照片测试",
            "导出挑战一材料包",
            "按硬件说明迁移到行空板",
        ],
    ),
    TaskDefinition(
        slug="heritage_ocr_typo",
        title="挑战二：了解非遗专业知识",
        summary="为知识卡片文字识别、错别字定位和更正播报生成程序骨架。",
        student_goal="生成可改造的 OCR 结果校验和错别字播报模板。",
        group="小学/初中/高中",
        requirement_source="附件5 智能博物 常规挑战二",
        competition_requirements=[
            "识别任务二卡片触发挑战",
            "实时拍照识别知识卡片文字",
            "小学定位1个错别字",
            "初中/高中定位2个错别字",
            "按规定格式显示并播报更正结果",
        ],
        ai_capability="ocr_typo_checker",
        sample_dataset_kind="ocr",
        runtime_requirements=["easyocr", "torch", "opencv-python-headless"],
        voice_profile="dfrobot_tts_broadcast",
        paused_features=[],
        suggested_hardware=["unihiker_m10"],
        required_outputs=STANDARD_OUTPUTS,
        starter_steps=[
            "输入正确的知识卡片文字",
            "保存正确文字",
            "输入带错字的文字测试",
            "导出挑战二材料包",
            "按硬件说明迁移到行空板",
        ],
    ),
    TaskDefinition(
        slug="heritage_text_classifier",
        title="挑战三：非遗文化分类学览",
        summary="把少量非遗词语或说明文本整理成可运行的分类示例。",
        student_goal="训练一个判断词语属于哪类非遗的文本分类模型，输出格式：XXX属于XXX。",
        group="小学/初中/高中",
        requirement_source="附件5 智能博物 常规挑战三",
        competition_requirements=[
            "实时拍照识别词语卡片",
            "训练并调用自建文本分类模型",
            "展示与播报格式：XXX属于XXX",
            "展示环节识别现场抽取的3-6张词语卡片",
            "全部挑战任务结束后播报提示语：挑战完成",
        ],
        ai_capability="text_classifier",
        sample_dataset_kind="text",
        runtime_requirements=["scikit-learn", "joblib", "numpy"],
        voice_profile="dfrobot_tts_broadcast",
        paused_features=[],
        suggested_hardware=["unihiker_m10"],
        required_outputs=STANDARD_OUTPUTS,
        starter_steps=[
            "添加非遗类别并粘贴词语例句",
            "点击训练查看准确率",
            "输入新词语测试",
            "导出挑战三材料包",
            "按硬件说明迁移到行空板",
        ],
    ),
    TaskDefinition(
        slug="heritage_sentence_classifier",
        title="挑战四：非遗文化深化认知",
        summary="为句子卡片识别、非遗类别和名称判断生成文本分类模板。",
        student_goal="生成符合“这是非遗XXX类别的XXX”格式的分类脚本。",
        group="小学/初中/高中",
        requirement_source="附件5 智能博物 常规挑战四",
        competition_requirements=[
            "识别任务四卡片触发挑战",
            "实时识别句子卡片",
            "训练并调用自建文本分类模型",
            "识别3-6张现场抽取句子卡片",
            "播报格式：这是非遗XXX类别的XXX",
            "全部挑战任务结束后播报提示语：挑战完成",
        ],
        ai_capability="text_classifier",
        sample_dataset_kind="text",
        runtime_requirements=["scikit-learn", "joblib", "numpy"],
        voice_profile="dfrobot_tts_broadcast",
        paused_features=[],
        suggested_hardware=["unihiker_m10"],
        required_outputs=STANDARD_OUTPUTS,
        starter_steps=[
            "添加类别并粘贴句子例句",
            "点击训练查看准确率",
            "输入新句子测试",
            "导出挑战四材料包",
            "按硬件说明迁移到行空板",
        ],
    ),
    TaskDefinition(
        slug="heritage_qa_helper",
        title="非遗知识问答模板",
        summary="把竞赛知识材料整理成固定问答程序模板。",
        student_goal="训练一个能根据问题找到最相关答案的检索式问答助手。",
        group="创意拓展",
        requirement_source="附件5 智能博物 创意拓展",
        competition_requirements=[
            "围绕非遗传承与宣传主题",
            "不得和常规挑战一至四重复",
            "突出图像识别、语音识别、自然语言处理等人工智能技术",
            "提交创作说明、程序代码、作品照片和2分钟内演示视频",
        ],
        ai_capability="qa_retrieval",
        sample_dataset_kind="qa",
        runtime_requirements=["scikit-learn", "joblib", "numpy"],
        voice_profile="dfrobot_tts_broadcast",
        paused_features=["语音识别"],
        suggested_hardware=["unihiker_m10"],
        required_outputs=STANDARD_OUTPUTS,
        starter_steps=[
            "每行录入一组问答",
            "点击训练建立问答索引",
            "输入新问题测试",
            "导出创意拓展材料包",
            "补充作品照片和说明",
        ],
    ),
]

FUTURE_CREATOR_TASKS = [
    TaskDefinition(
        slug="image_recognition_starter",
        title="图像识别快速模板",
        summary="生成一个适合学生改造的图像识别项目骨架。",
        student_goal="生成可在电脑或边缘设备上继续修改的图像识别脚本和说明。",
        group="小学/初中/高中",
        requirement_source="附件4 优创未来 图像识别规定技术要求",
        competition_requirements=[
            "现场发布4类卡片",
            "小学自选1类完成识别",
            "初中/高中自选2类完成识别",
            "展示环节由专家指定一种识别",
        ],
        ai_capability="image_classifier",
        sample_dataset_kind="image",
        runtime_requirements=["scikit-learn", "joblib", "numpy", "pillow", "onnxruntime"],
        voice_profile="none",
        paused_features=[],
        suggested_hardware=["unihiker_m10"],
        required_outputs=STANDARD_OUTPUTS,
        starter_steps=[
            "添加卡片类别并上传图片",
            "点击训练查看准确率",
            "上传新图片测试",
            "导出比赛材料包",
            "按硬件说明迁移到行空板",
        ],
    ),
    TaskDefinition(
        slug="sensor_decision_template",
        title="传感器决策程序模板",
        summary="生成一个读取输入、判断状态、输出动作的硬件控制程序骨架。",
        student_goal="生成适合接入行空板 M10 与 DFRobot 传感器/执行器外设的决策逻辑示例。",
        group="创意应用",
        requirement_source="附件4 优创未来 具身智能与智慧医疗",
        competition_requirements=[
            "围绕具身智能、智慧医疗设计创意应用",
            "完成方案设计、硬件搭建、程序编写和软件调试",
            "体现认知、推理、决策等类人智能功能",
            "提交创作说明、演示视频和实物照片",
        ],
        ai_capability="sensor_decision_model",
        sample_dataset_kind="sensor",
        runtime_requirements=["scikit-learn", "joblib", "numpy"],
        voice_profile="none",
        paused_features=["真实传感器连接", "真实执行器控制"],
        suggested_hardware=["unihiker_m10"],
        required_outputs=STANDARD_OUTPUTS,
        starter_steps=[
            "设计输入信号和动作",
            "粘贴传感器CSV数据",
            "点击训练并查看决策规则",
            "输入新数值测试",
            "导出比赛材料包",
        ],
    ),
    TaskDefinition(
        slug="primary_voice_image_interaction",
        title="小学组：语音互动与单类图像识别",
        summary="为关键词语音互动和1类卡片识别生成轻量模板。",
        student_goal="生成小学组规定技术要求的程序与材料清单。",
        group="小学组",
        requirement_source="附件4 优创未来 小学组规定技术要求",
        competition_requirements=[
            "基于关键词识别的人机语音互动1条",
            "具体关键词现场发布",
            "4类卡片中自选1类完成识别",
            "可包含语音合成、语音交互控制、运动控制",
        ],
        ai_capability="image_classifier",
        sample_dataset_kind="image",
        runtime_requirements=["scikit-learn", "joblib", "numpy", "pillow", "onnxruntime"],
        voice_profile="unihiker_keyword_voice",
        paused_features=[],
        suggested_hardware=["unihiker_m10"],
        required_outputs=STANDARD_OUTPUTS,
        starter_steps=[
            "选择1类卡片并上传图片",
            "点击训练查看准确率",
            "上传新图片测试",
            "导出材料包并配置现场关键词",
            "按硬件说明迁移到行空板",
        ],
    ),
    TaskDefinition(
        slug="junior_model_calling_workflow",
        title="初中组：视觉模型训练与调用",
        summary="为关键词语音互动、2类卡片识别和模型调用生成项目骨架。",
        student_goal="生成初中组模型训练、调用和硬件迁移材料。",
        group="初中组",
        requirement_source="附件4 优创未来 初中组规定技术要求",
        competition_requirements=[
            "基于关键词识别的人机语音互动1条",
            "4类卡片中自选2类完成识别",
            "体现视觉模型训练和模型调用",
            "可结合自然语言处理和运动控制",
        ],
        ai_capability="image_classifier",
        sample_dataset_kind="image",
        runtime_requirements=["scikit-learn", "joblib", "numpy", "pillow", "onnxruntime"],
        voice_profile="unihiker_keyword_voice",
        paused_features=[],
        suggested_hardware=["unihiker_m10"],
        required_outputs=STANDARD_OUTPUTS,
        starter_steps=[
            "添加2类卡片并上传图片",
            "点击训练查看准确率",
            "上传新图片测试",
            "导出材料包并配置现场关键词",
            "按硬件说明迁移到行空板",
        ],
    ),
    TaskDefinition(
        slug="senior_llm_vision_motion",
        title="高中组：大模型语音互动、视觉识别与运动控制",
        summary="为行空板 M10 + DFRobot 外设路线生成高中组视觉识别、语音接口和运动控制方案骨架。",
        student_goal="生成高中组完整技术链路的程序模板和验收清单。",
        group="高中组（含中职）",
        requirement_source="附件4 优创未来 高中组规定技术要求",
        competition_requirements=[
            "基于人工智能大模型的人机语音互动",
            "大模型智能体角色设定须与现场任务主题相符",
            "4类卡片中自选2类完成识别",
            "使用机械装置自主夹取3个轻质立方体并摆放",
        ],
        ai_capability="image_classifier",
        sample_dataset_kind="image",
        runtime_requirements=["scikit-learn", "joblib", "numpy", "pillow", "onnxruntime"],
        voice_profile="unihiker_keyword_voice",
        paused_features=["真实大模型智能体", "真实机械装置控制", "行空板M10本地大模型需外接服务或后续扩展"],
        suggested_hardware=["unihiker_m10"],
        required_outputs=STANDARD_OUTPUTS,
        starter_steps=[
            "添加2类卡片并上传图片",
            "点击训练查看准确率",
            "上传新图片测试",
            "导出比赛材料包",
            "按说明接入语音和运动控制",
        ],
    ),
]

GENERAL_TASKS = [
    TaskDefinition(
        slug="general_image_classifier",
        title="图像分类",
        summary="上传几类图片，训练一个能认出新图片属于哪一类的模型。",
        student_goal="理解图像分类的完整流程：采集数据、训练、测试、导出。",
        group="通用练习",
        requirement_source="机器学习基础练习",
        competition_requirements=[
            "准备至少2个类别的图片，每类2张以上",
            "训练后查看准确率",
            "用一张新图片测试模型",
            "导出材料包并在电脑上运行验证",
        ],
        ai_capability="image_classifier",
        sample_dataset_kind="image",
        runtime_requirements=["scikit-learn", "joblib", "numpy", "pillow", "onnxruntime"],
        voice_profile="none",
        paused_features=[],
        suggested_hardware=["student_laptop"],
        required_outputs=STANDARD_OUTPUTS,
        starter_steps=[
            "添加图片类别",
            "每类上传几张图片",
            "点击训练",
            "上传新图片测试",
            "导出材料包",
        ],
    ),
    TaskDefinition(
        slug="general_text_classifier",
        title="文本分类",
        summary="给几类文字示例，训练一个能判断新句子属于哪一类的模型。",
        student_goal="理解文本分类的完整流程：整理语料、训练、测试、导出。",
        group="通用练习",
        requirement_source="机器学习基础练习",
        competition_requirements=[
            "准备至少2个类别的文本，每类3条以上",
            "训练后查看准确率",
            "输入一条新文本测试模型",
            "导出材料包并在电脑上运行验证",
        ],
        ai_capability="text_classifier",
        sample_dataset_kind="text",
        runtime_requirements=["scikit-learn", "joblib", "numpy"],
        voice_profile="none",
        paused_features=[],
        suggested_hardware=["student_laptop"],
        required_outputs=STANDARD_OUTPUTS,
        starter_steps=[
            "添加文本类别",
            "每类粘贴几条例句",
            "点击训练",
            "输入新句子测试",
            "导出材料包",
        ],
    ),
    TaskDefinition(
        slug="general_audio_classifier",
        title="语音分类",
        summary="给几类声音录音，训练一个能听出新声音属于哪一类的模型。",
        student_goal="理解声音分类的完整流程：录音、提取特征、训练、测试、导出。",
        group="通用练习",
        requirement_source="机器学习基础练习",
        competition_requirements=[
            "准备至少2个类别的声音，每类2段以上",
            "用页面录音按钮录制，或上传 WAV 文件",
            "训练后录一段新声音测试",
            "导出材料包并在电脑上运行验证",
        ],
        ai_capability="audio_classifier",
        sample_dataset_kind="audio",
        runtime_requirements=["scikit-learn", "joblib", "numpy"],
        voice_profile="none",
        paused_features=[],
        suggested_hardware=["student_laptop"],
        required_outputs=STANDARD_OUTPUTS,
        starter_steps=[
            "添加声音类别",
            "每类录几段声音",
            "点击训练",
            "录新声音测试",
            "导出材料包",
        ],
    ),
    TaskDefinition(
        slug="general_qa_retrieval",
        title="智能问答",
        summary="录入问答对，做一个能根据问题找到最相关答案的小助手。",
        student_goal="理解检索式问答的原理：相似度匹配和置信度。",
        group="通用练习",
        requirement_source="机器学习基础练习",
        competition_requirements=[
            "录入至少3组问答对",
            "训练后用新问题测试",
            "观察相似度分数和兜底回答",
            "导出材料包并在电脑上运行验证",
        ],
        ai_capability="qa_retrieval",
        sample_dataset_kind="qa",
        runtime_requirements=["scikit-learn", "joblib", "numpy"],
        voice_profile="none",
        paused_features=[],
        suggested_hardware=["student_laptop"],
        required_outputs=STANDARD_OUTPUTS,
        starter_steps=[
            "整理问答知识点",
            "每行录入一组问答",
            "点击训练",
            "输入新问题测试",
            "导出材料包",
        ],
    ),
    TaskDefinition(
        slug="general_sensor_decision",
        title="传感器决策",
        summary="粘贴传感器数据表格，训练一个根据数值判断动作的决策树。",
        student_goal="理解决策树：模型如何从数据中学出 if-else 规则。",
        group="通用练习",
        requirement_source="机器学习基础练习",
        competition_requirements=[
            "准备带表头的CSV数据，最后一列是动作",
            "每种动作至少2行数据",
            "训练后查看决策规则",
            "输入一行新数值测试模型",
        ],
        ai_capability="sensor_decision_model",
        sample_dataset_kind="sensor",
        runtime_requirements=["scikit-learn", "joblib", "numpy"],
        voice_profile="none",
        paused_features=[],
        suggested_hardware=["student_laptop"],
        required_outputs=STANDARD_OUTPUTS,
        starter_steps=[
            "设计输入信号和动作",
            "粘贴CSV数据",
            "点击训练并查看规则",
            "输入新数值测试",
            "导出材料包",
        ],
    ),
]

GENERAL_ML = CompetitionDefinition(
    slug="general_ml",
    title="机器学习任务",
    summary="不挂竞赛的基础练习：图像分类、文本分类、智能问答、传感器决策。",
    tasks=GENERAL_TASKS,
)

COMPETITIONS = [
    CompetitionDefinition(
        slug="smart_museum",
        title="智能博物",
        summary="适合先验证轻量工作流：文本分类、知识问答、作品材料整理。",
        tasks=SMART_MUSEUM_TASKS,
    ),
    CompetitionDefinition(
        slug="future_creator",
        title="优创未来",
        summary="面向硬件和应用编程：图像识别、传感器决策、边缘部署准备。",
        tasks=FUTURE_CREATOR_TASKS,
    ),
]


def normalize_edition(edition: AppEdition | str | None = "all") -> AppEdition:
    if edition in ("smart_museum", "future_creator"):
        return edition
    return "all"


def list_competitions(edition: AppEdition | str | None = "all") -> list[CompetitionDefinition]:
    normalized = normalize_edition(edition)
    if normalized == "all":
        return COMPETITIONS
    return [competition for competition in COMPETITIONS if competition.slug == normalized]


def get_competition(
    slug: str,
    edition: AppEdition | str | None = "all",
) -> CompetitionDefinition | None:
    # 通用任务组在所有版本都可用，不参与竞赛版本过滤。
    if slug == GENERAL_ML.slug:
        return GENERAL_ML
    return next((competition for competition in list_competitions(edition) if competition.slug == slug), None)


def get_task(
    competition_slug: str,
    task_slug: str,
    edition: AppEdition | str | None = "all",
) -> TaskDefinition | None:
    competition = get_competition(competition_slug, edition)
    if competition is None:
        return None
    return next((task for task in competition.tasks if task.slug == task_slug), None)
